FROM postgres:16-alpine

COPY migrations/ /migrations/

ENTRYPOINT ["sh", "-c"]
CMD ["for migration in /migrations/*.up.sql; do echo \"Applying ${migration}\"; psql -v ON_ERROR_STOP=1 \"$DB_URL\" -f \"$migration\"; done"]

