#!/usr/bin/env python3
"""Generate a reviewable, transactional GeoNames country refresh migration.

Only reads ZIP files and writes SQL; never connects to a database.
"""
import argparse
import datetime
import hashlib
import io
import math
from pathlib import Path
import re
import tempfile
import urllib.request
import zipfile

COLUMNS = ('geonameid name asciiname alternatenames latitude longitude feature_class '
           'feature_code country_code cc2 admin1_code admin2_code admin3_code admin4_code '
           'population elevation dem timezone modification_date').split()
PLACE_CODES = frozenset('PPL PPLA PPLA2 PPLA3 PPLA4 PPLA5 PPLC PPLF PPLG PPLL PPLR PPLS PPLX STLMT'.split())
NUMERIC = {0, 4, 5, 14, 15, 16}


def read_places(archive, country):
    with zipfile.ZipFile(archive) as z:
        with z.open(country + '.txt') as raw:
            rows = {}
            for line_number, line in enumerate(io.TextIOWrapper(raw, encoding='utf-8'), 1):
                fields = line.rstrip('\r\n').split('\t')
                if len(fields) != 19:
                    raise ValueError(f'line {line_number}: expected 19 fields')
                if fields[8] != country:
                    raise ValueError(f'line {line_number}: unexpected country')
                if fields[6] != 'P' or fields[7] not in PLACE_CODES:
                    continue
                ident = int(fields[0])
                if ident <= 0 or ident in rows:
                    raise ValueError(f'line {line_number}: invalid or duplicate ID')
                lat, lon = float(fields[4]), float(fields[5])
                if not (math.isfinite(lat) and math.isfinite(lon) and -90 <= lat <= 90 and -180 <= lon <= 180):
                    raise ValueError(f'line {line_number}: invalid coordinates')
                if not fields[1] or not fields[17]:
                    raise ValueError(f'line {line_number}: missing name or timezone')
                for index in (14, 15, 16):
                    if fields[index]:
                        int(fields[index])
                if int(fields[14] or '0') < 0:
                    raise ValueError(f'line {line_number}: negative population')
                datetime.date.fromisoformat(fields[18])
                rows[ident] = fields
    if not rows:
        raise ValueError('archive contains no current populated places')
    return [rows[key] for key in sorted(rows)]


def sql_value(value, index):
    if value == '':
        return 'NULL'
    if index in NUMERIC:
        return str(float(value)) if index in (4, 5) else str(int(value))
    return "E'" + value.replace('\\', '\\\\').replace("'", "''") + "'"


def write_migration(output, rows, country, digest):
    output.write(f'-- GeoNames {country}: {len(rows)} current populated places; no population threshold.\n')
    output.write(f'-- Source: https://download.geonames.org/export/dump/{country}.zip\n')
    output.write(f'-- Retrieved: {datetime.date.today().isoformat()}; archive SHA-256: {digest}\n')
    output.write('-- Attribution: GeoNames, https://www.geonames.org/ (CC BY 4.0).\n')
    output.write('-- Generated by scripts/refresh_geonames.py. Upserts only; no deletions.\n')
    output.write('-- Equal-date records are refreshed; newer local records are preserved.\nBEGIN;\n')
    assignments = ',\n  '.join(f'{col} = EXCLUDED.{col}' for col in COLUMNS[1:])
    for start in range(0, len(rows), 500):
        output.write('INSERT INTO public.all_countries (' + ', '.join(COLUMNS) + ') VALUES\n')
        output.write(',\n'.join('(' + ', '.join(sql_value(v, i) for i, v in enumerate(row)) + ')' for row in rows[start:start+500]))
        output.write('\nON CONFLICT (geonameid) DO UPDATE SET\n  ' + assignments)
        output.write('\nWHERE all_countries.modification_date IS NULL\n   OR EXCLUDED.modification_date >= all_countries.modification_date;\n')
    output.write('ANALYZE public.all_countries;\nCOMMIT;\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--country', required=True, help='ISO two-letter country code')
    parser.add_argument('--archive', type=Path, help='use a previously downloaded official country ZIP')
    parser.add_argument('--output', required=True, type=Path, help='new SQL file; existing files are never overwritten')
    args = parser.parse_args()
    country = args.country.upper()
    if not re.fullmatch('[A-Z]{2}', country):
        parser.error('country must contain exactly two ASCII letters')
    if args.output.exists():
        parser.error('output already exists; choose a new migration number')
    with tempfile.TemporaryDirectory(prefix='geonames-') as temp:
        archive = args.archive or Path(temp) / (country + '.zip')
        if args.archive is None:
            url = f'https://download.geonames.org/export/dump/{country}.zip'
            with urllib.request.urlopen(url, timeout=120) as response, archive.open('wb') as target:
                while chunk := response.read(1024 * 1024):
                    target.write(chunk)
        rows = read_places(archive, country)
        digest = hashlib.sha256(archive.read_bytes()).hexdigest()
        with args.output.open('x', encoding='utf-8') as output:
            write_migration(output, rows, country, digest)
    print(f'Wrote {len(rows)} places to {args.output}')


if __name__ == '__main__':
    main()
